### PR TITLE
ytproxy bug and resources

### LINKED ISSUE #4: [piped] Please add option to set resource requests and limits, and also add default ones
### Helm chart name

piped

### Describe the solution you'd like

Add option to set resource requests and limits

In addition to that set default requests and limits:
```yaml
frontend:
      resources:
        requests:
          cpu: 32m
          memory: 32Mi
        limits:
          cpu: 128m
          memory: 128Mi
backend:
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          cpu: 1500m
          memory: 1500Mi
ytproxy:
      resources:
        requests:
          cpu: 32m
          memory: 32Mi
        limits:
          cpu: 500m
          memory: 500Mi
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by aleksasiriski**
fixed missing .ytproxy in pod template and fixed resources

fixes #4

### CODE REVIEW

**Review by samip5 — APPROVED** [review]
LGTM and thanks for fixing! Much appreciated.

**Review by samip5 — CHANGES_REQUESTED** [review]
Please make sure the changelog check at least passes.

**Comment by aleksasiriski** [comment]
None of the scripts don't seem to do anything, and I don't get what is wrong with my PR and why do I need to regenerate your docs?

**Comment by aleksasiriski** [comment]
> `$ .github/scripts/gen-helm-docs.sh apps piped`: That worked fine, wdym it doesn't do anything?

`bash .github/scripts/gen-helm-docs.sh`

```sh
-] Copying templates to /somewhere/Piped-Kubernetes/charts/apps/piped
cp: not replacing '/somewhere/Piped-Kubernetes/charts/apps/piped/README_CONFIG.md.gotmpl'
INFO[2023-05-03T22:28:54+02:00] Found Chart directories [apps/piped]         
INFO[2023-05-03T22:28:54+02:00] Generating README Documentation for chart /somewhere/Piped-Kubernetes/charts/apps/piped 
WARN[2023-05-03T22:28:54+02:00] Error generating gotemplates for chart /somewhere/Piped-Kubernetes/charts/apps/piped: template: /somewhere/Piped-Kubernetes/charts/apps/piped:117: function "fromYaml" not defined
```

**Comment by aleksasiriski** [comment]
```sh
bash .github/scripts/check-releasenotes.sh charts/apps/piped
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          [jq_filter] [files ...]
yq: error: argument files: can't open '.annotations."artifacthub.io/changes"': [Errno 2] No such file or directory: '.annotations."artifacthub.io/changes"'
```

**Comment by aleksasiriski** [comment]
```sh
python .github/scripts/renovate-releasenotes.py apps/piped/
Trying to determine default branch...
Comparing against branch origin/HEAD
Updating changelog annotation for chart charts/apps/piped
```

this doesn't produce any changes that i can commit

**Comment by samip5** [comment]
> ```shell
> bash .github/scripts/check-releasenotes.sh charts/apps/piped
> usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
>           [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
>           [--indentless-lists] [--in-place] [--version]
>           [jq_filter] [files ...]
> yq: error: argument files: can't open '.annotations."artifacthub.io/changes"': [Errno 2] No such file or directory: '.annotations."artifacthub.io/changes"'
> ```

It's not the same thing to invoke it with bash and w/o.

`.github/scripts/check-releasenotes.sh charts/apps/piped` vs `bash .github/scripts/check-releasenotes.sh charts/apps/piped` is not the same thing and the first one does indeed work while the latter doesn't for me either.

**Comment by aleksasiriski** [comment]
If those scripts DO in fact work for you, wouldn't it be easier to just merge this request to another branch, run those scripts and after that merge to main?

**Comment by aleksasiriski** [comment]
I believe it shoud be the same thing, I appended `bash` because I use fish. Running just `.github/scripts/check-releasenotes.sh charts/apps/piped` inside fish and inside bash produces the same error for me.

**Review by samip5 — APPROVED** [review]
It seems I need to fix those scripts at some point, but for now the changelog and readme are correct so I'm merging it despite the checks being unhappy.

**Comment by samip5** [comment]
> ```shell
> python .github/scripts/renovate-releasenotes.py apps/piped/
> Trying to determine default branch...
> Comparing against branch origin/HEAD
> Updating changelog annotation for chart charts/apps/piped
> ```
> 
> this doesn't produce any changes that i can commit

That one is meant to work only for Renovate PRs as seen here: https://github.com/TeamPiped/Piped-Kubernetes/blob/main/.github/workflows/charts-changelog.yaml#L65

**Pull request merged**
